language: java

jdk:
  - openjdk11

stages:
  - name: build
  - name: run
    if: branch = main

jobs:
  include:
    - stage: build
      script:
        - javac add.java
    - stage: run
      script:
        - javac add.java
        - java add