version: 2.1

jobs:
  build_and_run:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Compile Java program
          command: javac add.java
      - run:
          name: Run Java program
          command: java add

workflows:
  ci:
    jobs:
      - build_and_run
