version: 2.1

jobs:
  build-and-run:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Compile Java source
          command: javac Add.java
      - run:
          name: Run the demo app
          command: java Add

workflows:
  demo-workflow:
    jobs:
      - build-and-run
